import contextlib
import hashlib
import importlib.util
import io
import json
import os
import subprocess
import sys
import tarfile
import tempfile
import unittest
import zipfile
from pathlib import Path

from maimai_intelligence.catalog_refresh import METADATA_URLS
from maimai_intelligence.corpus_requests import preparation_request
from maimai_intelligence.corpus_update import prepare_corpus
from maimai_intelligence.lab import build_lab
from maimai_intelligence.registry import write_registry
from tests.lab_fixture import write_package
from tests.mai_notes_fixture import encoded
from tests.mai_notes_fixture import manifest as source_manifest
from tests.registry_fixture import fixture


class DistributionTests(unittest.TestCase):
    def test_wheel_runs_without_report_package_or_source_checkout(self):
        root = Path(__file__).resolve().parents[1]
        spec = importlib.util.spec_from_file_location(
            "isolated_backend", root / "build_backend/maimai_build_backend.py"
        )
        backend = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(backend)
        previous = Path.cwd()
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory)
            try:
                os.chdir(root)
                wheel = backend.build_wheel(directory)
                source = backend.build_sdist(directory)
                self.assertTrue((destination / source).is_file())
            finally:
                os.chdir(previous)
            unpacked = destination / "unpacked"
            with tarfile.open(destination / source) as source_archive:
                source_archive.extractall(unpacked, filter="data")
            source_root = unpacked / f"{backend.DISPLAY_NAME}-{backend.VERSION}"
            for line in (source_root / "requirements-dev.txt").read_text().splitlines():
                if line.startswith("-r "):
                    self.assertTrue((source_root / line[3:].strip()).is_file(), line)
            rebuilt = destination / "rebuilt"
            try:
                os.chdir(source_root)
                rebuilt_wheel = backend.build_wheel(str(rebuilt))
            finally:
                os.chdir(previous)
            with (
                zipfile.ZipFile(destination / wheel) as direct,
                zipfile.ZipFile(rebuilt / rebuilt_wheel) as rebuilt_archive,
            ):
                self.assertEqual(direct.namelist(), rebuilt_archive.namelist())
                for name in direct.namelist():
                    self.assertEqual(direct.read(name), rebuilt_archive.read(name), name)
            installed = destination / "installed"
            with zipfile.ZipFile(destination / wheel) as archive:
                self.assertFalse(
                    any(name.startswith("maimai_report/") for name in archive.namelist())
                )
                archive.extractall(installed)  # noqa: S202 - ZIP generated by this test, not a tar archive.
            code = """
import sys, pathlib, importlib.abc
sys.path.insert(0,sys.argv[1])
class BlockReport(importlib.abc.MetaPathFinder):
 def find_spec(self,fullname,*args):
  if fullname.startswith("maimai_report"): raise RuntimeError("Report dependency forbidden")
sys.meta_path.insert(0,BlockReport())
from maimai_intelligence.cli import main
from maimai_intelligence.bundles import export_report_bundle
from maimai_intelligence.catalog_refresh import refresh
from maimai_intelligence.catalog_sources import wiki_catalog
from maimai_intelligence.catalog_transcriptions import implementation
assert callable(refresh) and callable(wiki_catalog)
assert "count_validator" in implementation()
assert main(["demo","--output",sys.argv[2]])==0
assert pathlib.Path(sys.argv[2],"index.html").is_file()
"""
            result = subprocess.run(  # noqa: S603
                [sys.executable, "-I", "-c", code, str(installed), str(destination / "site")],
                cwd=directory,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            manifest = json.loads((destination / "site/manifest.json").read_text())
            self.assertEqual(manifest["schema_version"], "1.0.0")

            # Exercise the installed corpus application, not just demo rendering.
            inputs = destination / "corpus"
            legacy = inputs / "legacy"
            retained = write_package(legacy / "package", grouped=True, constants=True)
            charts = json.loads((retained / "catalog.json").read_bytes())
            (legacy / "links.json").write_bytes(encoded(charts))
            build_lab(retained, legacy / "browser", catalog_version="fictional-baseline")
            registry = inputs / "registry"
            accepted, legacy_catalog, retained = fixture(registry)
            retained.rename(registry / "package")
            write_registry(accepted, registry / "registry")
            build_lab(
                registry / "package", registry / "browser", catalog_version="fictional-baseline"
            )

            def fixture_source(url, headers):
                if url == METADATA_URLS["mai-notes"]:
                    return 200, json.dumps(source_manifest(legacy_catalog["catalog"])).encode(), {}
                raise OSError("Fictional provider unavailable")

            request = preparation_request(
                registry / "captured-store",
                registry / "browser",
                package=registry / "package",
                registry=registry / "registry",
                offline=False,
            )
            with contextlib.redirect_stdout(io.StringIO()):
                captured = prepare_corpus(request, source_fetcher=fixture_source)
            (registry / "captured-run.json").write_text(json.dumps({"run": str(captured)}))
            source = (root / "tests/corpus_wheel_acceptance.py").read_text()
            result = subprocess.run(  # noqa: S603 -- isolated local wheel and authored fixture.
                [sys.executable, "-I", "-c", source, str(installed), str(inputs)],
                cwd=directory,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            registration_source = (root / "tests/corpus_source_acceptance.py").read_text(
                encoding="utf-8"
            )
            registration_results = []
            for operation in ("prepare", "replay"):
                extension = subprocess.run(  # noqa: S603 -- isolated authored fixture and wheel.
                    [
                        sys.executable,
                        "-I",
                        "-c",
                        registration_source,
                        str(installed),
                        str(inputs),
                        operation,
                    ],
                    cwd=directory,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertEqual(extension.returncode, 0, extension.stderr)
                registration_results.append(json.loads(extension.stdout))
            acceptance = json.loads(result.stdout)
            acceptance["source_registration"] = registration_results
            self.assertEqual(len(acceptance["cases"]), 2)
            self.assertEqual(acceptance["forbidden_attempts"], [])
            acceptance["wheel_sha256"] = hashlib.sha256(
                (destination / wheel).read_bytes()
            ).hexdigest()
            acceptance["sdist_wheel_contents_equal"] = True
            if output := os.environ.get("MAIMAI_REGISTRY_OUTPUT"):
                evidence = Path(output) / "corpus-wheel-acceptance.json"
                evidence.parent.mkdir(parents=True, exist_ok=True)
                evidence.write_text(json.dumps(acceptance, indent=2) + "\n")
