/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false --env-interface=StagingPagesEnv pages-bindings.d.ts` (hash: e546fe4966b44aa7fa41aa06223d2619)
interface __BaseEnv_StagingPagesEnv {
	USAGE_COLLECTOR: Fetcher /* maimai-private-usage-staging */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_StagingPagesEnv {}
}
interface StagingPagesEnv extends __BaseEnv_StagingPagesEnv {}
